name: Benchmarking
channels:
  - r
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.0
  - arpack=3.7.0
  - alabaster=0.7.12
  - binutils_impl_linux-64=2.33.1
  - binutils_linux-64=2.33.1
  - bwidget=1.9.11
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - colormath=3.0.0
  - curl=7.69.1
  - cycler=0.10.0
  - decorator=5.0.9
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - glib=2.68.2
  - glpk=4.65
  - gmp=6.2.1
  - graphite2=1.3.14
  - gsl=2.4
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=2.8.1
  - icu=58.2
  - joblib=1.0.1
  - jpeg=9b
  - kiwisolver=1.3.1
  - krb5=1.17.1
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.69.1
  - libedit=3.1.20210216
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - liblapack=3.8.0
  - libllvm10=10.0.1
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.10
  - louvain=0.7.0
  - lz4-c=1.9.3
  - make=4.2.1
  - matplotlib-base=3.3.4
  - metis=5.1.0
  - mpfr=4.0.2
  - ncurses=6.2
  - networkx=2.5
  - numba=0.53.1
  - numpy=1.19.5
  - olefile=0.46
  - openjdk=8.0.152
  - openssl=1.1.1k
  - pango=1.45.3
  - pcre=8.44
  - pillow=8.2.0
  - pip=21.1.2
  - pixman=0.40.0
  - pot=0.7.0
  - pynndescent=0.5.2
  - pyparsing=2.4.7
  - python=3.6.13
  - python-dateutil=2.8.1
  - python-igraph=0.9.1
  - python-louvain=0.15
  - python_abi=3.6
  - r-abind=1.4_5
  - r-acepack=1.4.1
  - r-ape=5.5
  - r-askpass=1.0
  - r-assertthat=0.2.1
  - r-backports=1.1.4
  - r-base=3.6.1
  - r-base64enc=0.1_3
  - r-bh=1.69.0_1
  - r-bitops=1.0_7
  - r-callr=3.2.0
  - r-catools=1.18.2
  - r-checkmate=1.9.1
  - r-cli=1.1.0
  - r-clipr=0.6.0
  - r-clisymbols=1.2.0
  - r-cluster=2.0.8
  - r-codetools=0.2_16
  - r-colorspace=1.4_1
  - r-cowplot=1.1.1
  - r-crayon=1.3.4
  - r-crosstalk=1.1.1
  - r-curl=3.3
  - r-data.table=1.12.2
  - r-deldir=0.2_3
  - r-desc=1.2.0
  - r-devtools=2.0.2
  - r-dichromat=2.0_0
  - r-digest=0.6.18
  - r-dosnow=1.0.19
  - r-dplyr=0.8.0.1
  - r-dqrng=0.3.0
  - r-evaluate=0.13
  - r-fansi=0.4.0
  - r-fitdistrplus=1.1_3
  - r-fnn=1.1.3
  - r-foreach=1.4.4
  - r-foreign=0.8_71
  - r-formula=1.2_3
  - r-fs=1.2.7
  - r-future=1.21.0
  - r-future.apply=1.7.0
  - r-ggplot2=3.1.1
  - r-ggrepel=0.9.1
  - r-ggridges=0.5.3
  - r-gh=1.0.1
  - r-git2r=0.25.2
  - r-globals=0.14.0
  - r-glue=1.3.1
  - r-goftest=1.2_2
  - r-gplots=3.1.1
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-gtools=3.8.2
  - r-hexbin=1.28.1
  - r-highr=0.8
  - r-hmisc=4.2_0
  - r-htmltable=1.13.1
  - r-htmltools=0.3.6
  - r-htmlwidgets=1.3
  - r-httpuv=1.6.1
  - r-httr=1.4.0
  - r-ica=1.0_2
  - r-igraph=1.2.6
  - r-ini=0.3.1
  - r-irlba=2.3.3
  - r-iterators=1.0.10
  - r-jsonlite=1.6
  - r-kernsmooth=2.23_18
  - r-knitr=1.22
  - r-labeling=0.3
  - r-later=1.2.0
  - r-lattice=0.20_38
  - r-latticeextra=0.6_28
  - r-lazyeval=0.2.2
  - r-leiden=0.3.8
  - r-liger=0.5.0.9000
  - r-listenv=0.8.0
  - r-lmtest=0.9_38
  - r-lsei=1.3_0
  - r-magrittr=1.5
  - r-markdown=0.9
  - r-mass=7.3_51.3
  - r-matrix=1.2_17
  - r-matrixstats=0.58.0
  - r-mclust=5.4.7
  - r-memoise=1.1.0
  - r-mgcv=1.8_28
  - r-mime=0.6
  - r-miniui=0.1.1.1
  - r-mnormt=1.5_5
  - r-munsell=0.5.0
  - r-nlme=3.1_139
  - r-nnet=7.3_12
  - r-npsurv=0.5_0
  - r-openssl=1.3
  - r-parallelly=1.25.0
  - r-patchwork=1.1.1
  - r-pbapply=1.4_3
  - r-pillar=1.3.1
  - r-pkgbuild=1.0.3
  - r-pkgconfig=2.0.2
  - r-pkgload=1.0.2
  - r-plogr=0.2.0
  - r-plotly=4.9.3
  - r-plyr=1.8.4
  - r-png=0.1_7
  - r-polyclip=1.10_0
  - r-prettyunits=1.0.2
  - r-processx=3.3.0
  - r-promises=1.2.0.1
  - r-ps=1.3.0
  - r-psych=1.8.12
  - r-purrr=0.3.2
  - r-r6=2.4.0
  - r-rann=2.6.1
  - r-rann.l1=2.5.2
  - r-rcmdcheck=1.3.2
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.1
  - r-rcppannoy=0.0.18
  - r-rcpparmadillo=0.9.300.2.0
  - r-rcppeigen=0.3.3.5.0
  - r-rcppparallel=5.1.4
  - r-rcppprogress=0.4.2
  - r-remotes=2.0.4
  - r-reshape2=1.4.3
  - r-reticulate=1.12
  - r-riverplot=0.6
  - r-rlang=0.3.4
  - r-rocr=1.0_11
  - r-rpart=4.1_15
  - r-rprojroot=1.3_2
  - r-rspectra=0.16_0
  - r-rstudioapi=0.10
  - r-rsvd=1.0.3
  - r-rtsne=0.15
  - r-scales=1.0.0
  - r-sctransform=0.3.2
  - r-sessioninfo=1.1.1
  - r-seurat=3.2.0
  - r-shiny=1.3.2
  - r-sitmo=2.0.1
  - r-snow=0.4_3
  - r-sourcetools=0.1.7
  - r-spatstat=1.64_1
  - r-spatstat.data=2.1_0
  - r-spatstat.utils=2.1_0
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-survival=2.44_1.1
  - r-sys=3.2
  - r-tensor=1.5
  - r-tibble=2.1.1
  - r-tidyr=0.8.3
  - r-tidyselect=0.2.5
  - r-usethis=1.5.0
  - r-utf8=1.1.4
  - r-uwot=0.1.10
  - r-viridis=0.5.1
  - r-viridislite=0.3.0
  - r-whisker=0.3_2
  - r-withr=2.1.2
  - r-xfun=0.6
  - r-xopen=1.0.0
  - r-xtable=1.8_4
  - r-yaml=2.2.0
  - r-zoo=1.8_9
  - readline=8.1
  - scikit-learn=0.24.2
  - setuptools=52.0.0
  - six=1.16.0
  - spectra=0.0.11
  - sqlite=3.35.4
  - suitesparse=5.10.1
  - tbb=2020.3
  - texttable=1.6.3
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tktable=2.10
  - tornado=6.1
  - umap-learn=0.5.1
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - anndata==0.7.6
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - babel==2.9.1
    - backcall==0.2.0
    - bleach==3.3.0
    - cached-property==1.5.2
    - cffi==1.14.5
    - chardet==4.0.0
    - colorama==0.4.4
    - commonmark==0.9.1
    - cython==0.29.23
    - dataclasses==0.8
    - defusedxml==0.7.1
    - docutils==0.17.1
    - entrypoints==0.3
    - future==0.18.2
    - get-version==2.1
    - h5py==3.1.0
    - hyperopt==0.1.2
    - idna==2.10
    - imagesize==1.2.0
    - importlib-metadata==1.7.0
    - ipykernel==5.5.5
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==3.0.1
    - jsonschema==3.2.0
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - legacy-api-wrap==1.2
    - llvmlite==0.36.0
    - markupsafe==2.0.1
    - mistune==0.8.4
    - natsort==7.1.1
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.0
    - novosparc==0.4.3
    - numexpr==2.7.3
    - pandas==1.1.5
    - pandocfilters==1.4.3
    - parso==0.8.2
    - patsy==0.5.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.19
    - ptyprocess==0.7.0
    - pycparser==2.20
    - pygments==2.9.0
    - pymongo==3.11.4
    - pyrsistent==0.17.3
    - pyzmq==22.1.0
    - recommonmark==0.7.1
    - requests==2.25.1
    - rich==10.4.0
    - scanpy==1.7.2
    - scipy==1.5.4
    - scvi-tools==0.8.0b0
    - seaborn==0.11.1
    - send2trash==1.7.1
    - sinfo==0.3.4
    - snowballstemmer==2.1.0
    - sphinx==4.0.2
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - statsmodels==0.12.2
    - stdlib-list==0.8.0
    - tables==3.6.1
    - terminado==0.10.1
    - testpath==0.5.0
    - torch==1.9.0
    - tqdm==4.61.1
    - traitlets==4.3.3
    - typing-extensions==3.10.0.0
    - urllib3==1.26.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - xlrd==1.2.0
    - stPlus==0.0.6
    - tangram-sc==1.0.0
